### ISSUE TITLE
fonts that need to be added

### ISSUE THREAD

**Issue by thecotne** [thecotne/georgian-webfonts#1]
this are fonts from `webfonts.cotne.com` some of them are not georgian fonts i will filter them later
BPG fonts are not here since i already added all of them
- [ ] ! Republic Helvetica Neue Extended
- [ ] !RepublicSloganGEORegular
- [ ] 3D Unicode
- [ ] AA Zuzumbo
- [ ] ALK Rounded Mtav Med
- [ ] ALK Sanet
- [ ] ALK Tall Mtavruli
- [ ] AS Grammatika
- [ ] AS Grammatika Geo Mtavruli 2
- [ ] AcadMtavr
- [ ] AcadNusx
- [ ] Adobe Arabic
- [ ] Agancxad
- [ ] Andantino script
- [ ] Arachveulebrivi Thin
- [ ] Archy EDT
- [ ] Arial
- [ ] Arial Black
- [ ] Arial Narrow
- [ ] Avaza
- [ ] BALAVARI
- [ ] BOG Nusxuri
- [ ] Babuka
- [ ] Chiller
- [ ] CollegiateHeavyOutline
- [ ] Comic Sans MS
- [ ] Cooper Black
- [ ] DejaVu Sans
- [ ] DejaVuSansBook
- [ ] Eka
- [ ] EkaHor
- [ ] Emilio 20
- [ ] FontAwesome
- [ ] Geo Kolkheti Mtavr
- [ ] Georgian Dream GC
- [ ] Grammatika
- [ ] Grammatika Light
- [ ] Helvetica
- [ ] Helvetica Condensed BQ
- [ ] Helvetica Neue
- [ ] HelveticaNeueLTStd-Roman
- [ ] Helvetica Neue LT Std
- [ ] Impact
- [ ] KA_LORTKIPANIDZE
- [ ] KG When Oceans Rise
- [ ] Kelson Sans
- [ ] LGV 2014 Mtavruli
- [ ] MG Glaho Drunk
- [ ] MT_Mchedlidze Helnatceri1
- [ ] Milford Condensed
- [ ] Myriad Pro
- [ ] Myriad Web Pro
- [ ] NeoSans
- [ ] Nexa Bold
- [ ] Nexa Light
- [ ] Norwester
- [ ] Noto Penekeko
- [ ] Oswald
- [ ] Roboto
- [ ] Sanet
- [ ] Snap ITC
- [ ] Source Sans Pro
- [ ] Stencil
- [ ] Sylfaen
- [ ] TBC Din Mtavruli
- [ ] Times New Roman
- [ ] Toyota Display
- [ ] Toyota Text
- [ ] Trench
- [ ] Viner Hand ITC
- [ ] Waltograph
- [ ] Zaza
- [ ] Zaza SP

**Comment by notgiorgi** [comment]
TBC ფონტები ხელმისაწვდომია უფასოდ?

**Comment by thecotne** [comment]
ეს სია აღებულია webfonts.cotne.com ზე ატვირთული ფაილებიდან და წარმოდგენა არ მაქვს "TBC Din Mtavruli" რა ხილია
