### ISSUE TITLE
support more font formats

### ISSUE THREAD

**Issue by thecotne** [thecotne/georgian-webfonts#2]
## Font Formats

| Name | Description |
| --- | --- |
| TTF | TrueType is an outline font standard developed by Apple and Microsoft in the late 1980s |
| OTF | OpenType developed by Microsoft with Adobe better version of TrueType |
| EOT | Embedded OpenType developed By Microsoft and supported only in Internet Explorer |
| SVG | SVG OpenType *depricated |
| WOFF | Web Open Font Format is compressed version of TrueType or OpenType |
| WOFF2 | is new version of WOFF with better compression |
## Browser Support of Font Formats

| Browser | WOFF | WOFF2 | OTF/TTF | SVG | EOT |
| --- | --- | --- | --- | --- | --- |
| Internet Explorer | 9 |  | 9 |  | 6 |
| FireFox | 3.6 | 39 | 3.5 |  |  |
| Chrome | 5 | 36 | 4 | 4 - 38 |  |
| Safari | 5.1 |  | 3.1 | 3.2 |  |
| Opera | 11.5 | 23 | 10.1 | 10.1 - 25 |  |
| IOS Safari | 5.1 |  | 4.3 | 3.2 |  |
| Opera Mini |  |  |  |  |  |
| Android Browser | 4.4 | 40 | 2.2 | 3 - 40 |  |
| Opera Mobile | 12 | 24 | 12 | 12 |  |
| Blackberry Browser | 7 |  | 7 | 7 |  |
| Chrome for Android | 42 | 42 | 42 |  |  |
| Firefox for Android | 37 |  | 37 |  |  |
| Internet Explorer Mobile | 10 |  | 10 |  |  |
| UC Browser for Android | 9.9 |  | 9.9 | 9.9 |  |

Can I use [WOFF](http://caniuse.com/woff), [WOFF2](http://caniuse.com/woff2), [OTF/TTF](http://caniuse.com/ttf), [EOT](http://caniuse.com/eot), [SVG fonts](http://caniuse.com/svg-fonts)
## Conclusions

woff2 is best but it's not widely supported

woff is very good format and it's supported in all major browsers

for old browsers that have some users you need ttf/otf

for old browsers that no one uses you can include SVG for IOS Safari 3.2, 4.1 and EOT for IE6,7,8

**Comment by thecotne** [comment]
create gulp package to convert fonts from ttf/otf to other formats

list of packages that can help
https://github.com/nfroidure/gulp-svgicons2svgfont
https://github.com/fontello/svg2ttf
https://github.com/fontello/ttf2woff
https://github.com/fontello/ttf2eot
https://github.com/qdsang/ttf2svg
https://github.com/morlay/gulp-ttf2svg
https://github.com/nfroidure/gulp-svg2ttf
https://github.com/nfroidure/gulp-ttf2woff
https://github.com/nfroidure/gulp-ttf2eot
https://github.com/ynakajima/ttf.js
https://github.com/nodebox/opentype.js

https://gist.github.com/sergeifilippov/58631bbaf5321dabb6cf
https://github.com/google/woff2

**Comment by Stichoza** [comment]
At least we can create configuration template for [fontsquirrel](http://www.fontsquirrel.com/tools/webfont-generator) and convert all fonts with one config file.

**Comment by Stichoza** [comment]
Example configuration [here](https://github.com/Stichoza/font-larisome/blob/master/src/fonts/generator_config.txt).

**Comment by thecotne** [comment]
@Stichoza ავტომატიზაცია მინდა 300+ ფონტი იქნება აქ მალე და ხელით ვერ დავაკონვერტებ ყველას (არც ვეცდები)

უკეთეს შემთხვევაში მინდა რომ gulp-ს და npm-ს არ გასცდეს ჩემი dependency ები
