### ISSUE TITLE
მოხალისეები

### ISSUE THREAD

**Issue by thecotne** [thecotne/georgian-webfonts#3]
ვეძებ მოხალისეებს ვინც
დააკონვერტირებს და დადებს ფონტებს პაკეტებს აქ https://github.com/georgian-webfonts
ვაკონვერტირებ ამ კონვერტორით https://everythingfonts.com/font-face
კონფიგურაცია არ ჭირდება არც ფონტის მოდიფიკაციას ახდენს უბრალოდ გადაყავს ყველა საჭირო ფორმატში და იძლევა css-ს

ვისაც გექნებათ სურვილი დაგამატებთ georgian-webfonts ის კონტრიბუტორებში და შეგეძლებათ რომ დაამატოთ ფონტები

ასევე თუ ფონტს აქვს რაიმე ხარვეზი georgian-webfonts ში რეპოზიტორიის დამატების შემდეგ issues ში ვწერთ (მაგ. ქართული და ლათინური სიმბოლოები არ უხდება ერთმანეტს აქვს შეუსაბამო სისქე სიმაღლე ან სტილი ან ფონტი შეიცავს ძალიან ბევრ სიმბოლოს რომლებიც არ არის ქართული საიტებისთვის "საჭირო" ან ფონტი შეიცავს მხოლოდ ქართულ სიმბოლოებს)
შემდეგ ვეცდები რომ ეს issue ები გავასწორებინო ავტორებს ან შეიძლება ფონტის ჩვენი ვერსიები გავაკეთოთ სხვა font family ით

**Comment by thecotne** [comment]
@Stichoza @giokaxo @maxtm8 @ShavidzeT

**Comment by Stichoza** [comment]
ვნახე კონვერტორი და ცუდია. ცუდი არაა, მაგრამ [fontrsquirrel webfont generator](http://www.fontsquirrel.com/tools/webfont-generator) უკეთესია. ქართული შრიფტები ძალიან არეულია baseline, size, x-height და ვებრი სხვა პარამეტრი. fontsqurrel იძლევა მაგის გასწორების საშუალებას Advanced mode-ზე რომ გადართავ.

ყველა რეპოს რომ გამოყვეს fontsquirrel-ის [generator_config.txt](https://github.com/Stichoza/font-larisome/blob/master/src/fonts/generator_config.txt), კარგი იქნება შემდგომი ცვლილებებისთვის.

**Comment by thecotne** [comment]
შეგიძლია დემონსტრაცია გააკეთო
რა ხარვეზი აქვს რაიმე კონკრეტულ ფონტს რომელიც სწორდება fontsquirrel ის მიერ

თუ ფონტს გადავაკეთებთ მერე ამანაც შეიძლება შექმნას პრობლემა
მაგალითად psd ში ორიგინალი ფონტია არის 18px ზე და ჩვენ საიტზე რო გამოვიტანთ იმ ფონტის გადაკეთებულ ვერსიას შეიძლება 18px იმხელა აღარ გამოვიდეს ან რაიმე სხვა მსგავსი პრობლემა შეიქმნას იმასთან დაკავშირებით რომ ჩვენ ფონტის ვერსია გვაქვს რომელიც 
უბრალოდ woff2 ში კიარ დავაკონვერტირეთ არამედ გადავაკეთეთ
